#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_QLCH__VTNN.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCH_VLNN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_CHITIETHOADON(tbl_CHITIETHOADON instance);
    partial void Updatetbl_CHITIETHOADON(tbl_CHITIETHOADON instance);
    partial void Deletetbl_CHITIETHOADON(tbl_CHITIETHOADON instance);
    partial void Inserttbl_CHITIETPHIEUNHAP(tbl_CHITIETPHIEUNHAP instance);
    partial void Updatetbl_CHITIETPHIEUNHAP(tbl_CHITIETPHIEUNHAP instance);
    partial void Deletetbl_CHITIETPHIEUNHAP(tbl_CHITIETPHIEUNHAP instance);
    partial void Inserttbl_HOADON(tbl_HOADON instance);
    partial void Updatetbl_HOADON(tbl_HOADON instance);
    partial void Deletetbl_HOADON(tbl_HOADON instance);
    partial void Inserttbl_KHACHHANG(tbl_KHACHHANG instance);
    partial void Updatetbl_KHACHHANG(tbl_KHACHHANG instance);
    partial void Deletetbl_KHACHHANG(tbl_KHACHHANG instance);
    partial void Inserttbl_LOAISANPHAM(tbl_LOAISANPHAM instance);
    partial void Updatetbl_LOAISANPHAM(tbl_LOAISANPHAM instance);
    partial void Deletetbl_LOAISANPHAM(tbl_LOAISANPHAM instance);
    partial void Inserttbl_NHACUNGCAP(tbl_NHACUNGCAP instance);
    partial void Updatetbl_NHACUNGCAP(tbl_NHACUNGCAP instance);
    partial void Deletetbl_NHACUNGCAP(tbl_NHACUNGCAP instance);
    partial void Inserttbl_NHANVIEN(tbl_NHANVIEN instance);
    partial void Updatetbl_NHANVIEN(tbl_NHANVIEN instance);
    partial void Deletetbl_NHANVIEN(tbl_NHANVIEN instance);
    partial void Inserttbl_PHIEUNHAP(tbl_PHIEUNHAP instance);
    partial void Updatetbl_PHIEUNHAP(tbl_PHIEUNHAP instance);
    partial void Deletetbl_PHIEUNHAP(tbl_PHIEUNHAP instance);
    partial void Inserttbl_SANPHAM(tbl_SANPHAM instance);
    partial void Updatetbl_SANPHAM(tbl_SANPHAM instance);
    partial void Deletetbl_SANPHAM(tbl_SANPHAM instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CNPM_QLCH__VTNN.Properties.Settings.Default.QLCH_VLNNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_CHITIETHOADON> tbl_CHITIETHOADONs
		{
			get
			{
				return this.GetTable<tbl_CHITIETHOADON>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CHITIETPHIEUNHAP> tbl_CHITIETPHIEUNHAPs
		{
			get
			{
				return this.GetTable<tbl_CHITIETPHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HOADON> tbl_HOADONs
		{
			get
			{
				return this.GetTable<tbl_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KHACHHANG> tbl_KHACHHANGs
		{
			get
			{
				return this.GetTable<tbl_KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LOAISANPHAM> tbl_LOAISANPHAMs
		{
			get
			{
				return this.GetTable<tbl_LOAISANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NHACUNGCAP> tbl_NHACUNGCAPs
		{
			get
			{
				return this.GetTable<tbl_NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NHANVIEN> tbl_NHANVIENs
		{
			get
			{
				return this.GetTable<tbl_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PHIEUNHAP> tbl_PHIEUNHAPs
		{
			get
			{
				return this.GetTable<tbl_PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<v_tbl_HOADON> v_tbl_HOADONs
		{
			get
			{
				return this.GetTable<v_tbl_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<v_loaisp> v_loaisps
		{
			get
			{
				return this.GetTable<v_loaisp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SANPHAM> tbl_SANPHAMs
		{
			get
			{
				return this.GetTable<tbl_SANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<v_Chitiethoadon> v_Chitiethoadons
		{
			get
			{
				return this.GetTable<v_Chitiethoadon>();
			}
		}
		
		public System.Data.Linq.Table<v_Thongkedoanhthu> v_Thongkedoanhthus
		{
			get
			{
				return this.GetTable<v_Thongkedoanhthu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CHITIETHOADON")]
	public partial class tbl_CHITIETHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaSP;
		
		private int _Soluong;
		
		private EntityRef<tbl_HOADON> _tbl_HOADON;
		
		private EntityRef<tbl_SANPHAM> _tbl_SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnSoluongChanging(int value);
    partial void OnSoluongChanged();
    #endregion
		
		public tbl_CHITIETHOADON()
		{
			this._tbl_HOADON = default(EntityRef<tbl_HOADON>);
			this._tbl_SANPHAM = default(EntityRef<tbl_SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._tbl_HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._tbl_SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HOADON_tbl_CHITIETHOADON", Storage="_tbl_HOADON", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public tbl_HOADON tbl_HOADON
		{
			get
			{
				return this._tbl_HOADON.Entity;
			}
			set
			{
				tbl_HOADON previousValue = this._tbl_HOADON.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HOADON.Entity = null;
						previousValue.tbl_CHITIETHOADONs.Remove(this);
					}
					this._tbl_HOADON.Entity = value;
					if ((value != null))
					{
						value.tbl_CHITIETHOADONs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("tbl_HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SANPHAM_tbl_CHITIETHOADON", Storage="_tbl_SANPHAM", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public tbl_SANPHAM tbl_SANPHAM
		{
			get
			{
				return this._tbl_SANPHAM.Entity;
			}
			set
			{
				tbl_SANPHAM previousValue = this._tbl_SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._tbl_SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_SANPHAM.Entity = null;
						previousValue.tbl_CHITIETHOADONs.Remove(this);
					}
					this._tbl_SANPHAM.Entity = value;
					if ((value != null))
					{
						value.tbl_CHITIETHOADONs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("tbl_SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CHITIETPHIEUNHAP")]
	public partial class tbl_CHITIETPHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPN;
		
		private string _MaSP;
		
		private int _Soluong;
		
		private string _TenSP;
		
		private double _GiaSP;
		
		private EntityRef<tbl_PHIEUNHAP> _tbl_PHIEUNHAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPNChanging(string value);
    partial void OnMaPNChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnSoluongChanging(int value);
    partial void OnSoluongChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnGiaSPChanging(double value);
    partial void OnGiaSPChanged();
    #endregion
		
		public tbl_CHITIETPHIEUNHAP()
		{
			this._tbl_PHIEUNHAP = default(EntityRef<tbl_PHIEUNHAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPN
		{
			get
			{
				return this._MaPN;
			}
			set
			{
				if ((this._MaPN != value))
				{
					if (this._tbl_PHIEUNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPNChanging(value);
					this.SendPropertyChanging();
					this._MaPN = value;
					this.SendPropertyChanged("MaPN");
					this.OnMaPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSP", DbType="Float NOT NULL")]
		public double GiaSP
		{
			get
			{
				return this._GiaSP;
			}
			set
			{
				if ((this._GiaSP != value))
				{
					this.OnGiaSPChanging(value);
					this.SendPropertyChanging();
					this._GiaSP = value;
					this.SendPropertyChanged("GiaSP");
					this.OnGiaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PHIEUNHAP_tbl_CHITIETPHIEUNHAP", Storage="_tbl_PHIEUNHAP", ThisKey="MaPN", OtherKey="MaPN", IsForeignKey=true)]
		public tbl_PHIEUNHAP tbl_PHIEUNHAP
		{
			get
			{
				return this._tbl_PHIEUNHAP.Entity;
			}
			set
			{
				tbl_PHIEUNHAP previousValue = this._tbl_PHIEUNHAP.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PHIEUNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PHIEUNHAP.Entity = null;
						previousValue.tbl_CHITIETPHIEUNHAPs.Remove(this);
					}
					this._tbl_PHIEUNHAP.Entity = value;
					if ((value != null))
					{
						value.tbl_CHITIETPHIEUNHAPs.Add(this);
						this._MaPN = value.MaPN;
					}
					else
					{
						this._MaPN = default(string);
					}
					this.SendPropertyChanged("tbl_PHIEUNHAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HOADON")]
	public partial class tbl_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaKH;
		
		private System.DateTime _Ngaylap;
		
		private string _MaNV;
		
		private EntitySet<tbl_CHITIETHOADON> _tbl_CHITIETHOADONs;
		
		private EntityRef<tbl_KHACHHANG> _tbl_KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgaylapChanging(System.DateTime value);
    partial void OnNgaylapChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public tbl_HOADON()
		{
			this._tbl_CHITIETHOADONs = new EntitySet<tbl_CHITIETHOADON>(new Action<tbl_CHITIETHOADON>(this.attach_tbl_CHITIETHOADONs), new Action<tbl_CHITIETHOADON>(this.detach_tbl_CHITIETHOADONs));
			this._tbl_KHACHHANG = default(EntityRef<tbl_KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tbl_KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="Date NOT NULL")]
		public System.DateTime Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HOADON_tbl_CHITIETHOADON", Storage="_tbl_CHITIETHOADONs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<tbl_CHITIETHOADON> tbl_CHITIETHOADONs
		{
			get
			{
				return this._tbl_CHITIETHOADONs;
			}
			set
			{
				this._tbl_CHITIETHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KHACHHANG_tbl_HOADON", Storage="_tbl_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tbl_KHACHHANG tbl_KHACHHANG
		{
			get
			{
				return this._tbl_KHACHHANG.Entity;
			}
			set
			{
				tbl_KHACHHANG previousValue = this._tbl_KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._tbl_KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_KHACHHANG.Entity = null;
						previousValue.tbl_HOADONs.Remove(this);
					}
					this._tbl_KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.tbl_HOADONs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tbl_KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CHITIETHOADONs(tbl_CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HOADON = this;
		}
		
		private void detach_tbl_CHITIETHOADONs(tbl_CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KHACHHANG")]
	public partial class tbl_KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _Diachi;
		
		private string _SDT;
		
		private EntitySet<tbl_HOADON> _tbl_HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public tbl_KHACHHANG()
		{
			this._tbl_HOADONs = new EntitySet<tbl_HOADON>(new Action<tbl_HOADON>(this.attach_tbl_HOADONs), new Action<tbl_HOADON>(this.detach_tbl_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KHACHHANG_tbl_HOADON", Storage="_tbl_HOADONs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tbl_HOADON> tbl_HOADONs
		{
			get
			{
				return this._tbl_HOADONs;
			}
			set
			{
				this._tbl_HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_HOADONs(tbl_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KHACHHANG = this;
		}
		
		private void detach_tbl_HOADONs(tbl_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LOAISANPHAM")]
	public partial class tbl_LOAISANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaloaiSP;
		
		private string _Tenloai;
		
		private string _Ghichu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaloaiSPChanging(string value);
    partial void OnMaloaiSPChanged();
    partial void OnTenloaiChanging(string value);
    partial void OnTenloaiChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public tbl_LOAISANPHAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaloaiSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaloaiSP
		{
			get
			{
				return this._MaloaiSP;
			}
			set
			{
				if ((this._MaloaiSP != value))
				{
					this.OnMaloaiSPChanging(value);
					this.SendPropertyChanging();
					this._MaloaiSP = value;
					this.SendPropertyChanged("MaloaiSP");
					this.OnMaloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this.OnTenloaiChanging(value);
					this.SendPropertyChanging();
					this._Tenloai = value;
					this.SendPropertyChanged("Tenloai");
					this.OnTenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NHACUNGCAP")]
	public partial class tbl_NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private string _Diachi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _Website;
		
		private EntitySet<tbl_PHIEUNHAP> _tbl_PHIEUNHAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    #endregion
		
		public tbl_NHACUNGCAP()
		{
			this._tbl_PHIEUNHAPs = new EntitySet<tbl_PHIEUNHAP>(new Action<tbl_PHIEUNHAP>(this.attach_tbl_PHIEUNHAPs), new Action<tbl_PHIEUNHAP>(this.detach_tbl_PHIEUNHAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NHACUNGCAP_tbl_PHIEUNHAP", Storage="_tbl_PHIEUNHAPs", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tbl_PHIEUNHAP> tbl_PHIEUNHAPs
		{
			get
			{
				return this._tbl_PHIEUNHAPs;
			}
			set
			{
				this._tbl_PHIEUNHAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PHIEUNHAPs(tbl_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NHACUNGCAP = this;
		}
		
		private void detach_tbl_PHIEUNHAPs(tbl_PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NHANVIEN")]
	public partial class tbl_NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private System.DateTime _Ngaysinh;
		
		private string _Diachi;
		
		private string _Quequan;
		
		private string _SDT;
		
		private double _LuongCB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnNgaysinhChanging(System.DateTime value);
    partial void OnNgaysinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnQuequanChanging(string value);
    partial void OnQuequanChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnLuongCBChanging(double value);
    partial void OnLuongCBChanged();
    #endregion
		
		public tbl_NHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quequan", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Quequan
		{
			get
			{
				return this._Quequan;
			}
			set
			{
				if ((this._Quequan != value))
				{
					this.OnQuequanChanging(value);
					this.SendPropertyChanging();
					this._Quequan = value;
					this.SendPropertyChanged("Quequan");
					this.OnQuequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float NOT NULL")]
		public double LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this.OnLuongCBChanging(value);
					this.SendPropertyChanging();
					this._LuongCB = value;
					this.SendPropertyChanged("LuongCB");
					this.OnLuongCBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PHIEUNHAP")]
	public partial class tbl_PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPN;
		
		private string _MaNCC;
		
		private string _MaNV;
		
		private System.DateTime _Ngaynhap;
		
		private EntitySet<tbl_CHITIETPHIEUNHAP> _tbl_CHITIETPHIEUNHAPs;
		
		private EntityRef<tbl_NHACUNGCAP> _tbl_NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPNChanging(string value);
    partial void OnMaPNChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgaynhapChanging(System.DateTime value);
    partial void OnNgaynhapChanged();
    #endregion
		
		public tbl_PHIEUNHAP()
		{
			this._tbl_CHITIETPHIEUNHAPs = new EntitySet<tbl_CHITIETPHIEUNHAP>(new Action<tbl_CHITIETPHIEUNHAP>(this.attach_tbl_CHITIETPHIEUNHAPs), new Action<tbl_CHITIETPHIEUNHAP>(this.detach_tbl_CHITIETPHIEUNHAPs));
			this._tbl_NHACUNGCAP = default(EntityRef<tbl_NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPN
		{
			get
			{
				return this._MaPN;
			}
			set
			{
				if ((this._MaPN != value))
				{
					this.OnMaPNChanging(value);
					this.SendPropertyChanging();
					this._MaPN = value;
					this.SendPropertyChanged("MaPN");
					this.OnMaPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(10)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tbl_NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaynhap", DbType="Date NOT NULL")]
		public System.DateTime Ngaynhap
		{
			get
			{
				return this._Ngaynhap;
			}
			set
			{
				if ((this._Ngaynhap != value))
				{
					this.OnNgaynhapChanging(value);
					this.SendPropertyChanging();
					this._Ngaynhap = value;
					this.SendPropertyChanged("Ngaynhap");
					this.OnNgaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PHIEUNHAP_tbl_CHITIETPHIEUNHAP", Storage="_tbl_CHITIETPHIEUNHAPs", ThisKey="MaPN", OtherKey="MaPN")]
		public EntitySet<tbl_CHITIETPHIEUNHAP> tbl_CHITIETPHIEUNHAPs
		{
			get
			{
				return this._tbl_CHITIETPHIEUNHAPs;
			}
			set
			{
				this._tbl_CHITIETPHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NHACUNGCAP_tbl_PHIEUNHAP", Storage="_tbl_NHACUNGCAP", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tbl_NHACUNGCAP tbl_NHACUNGCAP
		{
			get
			{
				return this._tbl_NHACUNGCAP.Entity;
			}
			set
			{
				tbl_NHACUNGCAP previousValue = this._tbl_NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NHACUNGCAP.Entity = null;
						previousValue.tbl_PHIEUNHAPs.Remove(this);
					}
					this._tbl_NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.tbl_PHIEUNHAPs.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tbl_NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CHITIETPHIEUNHAPs(tbl_CHITIETPHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PHIEUNHAP = this;
		}
		
		private void detach_tbl_CHITIETPHIEUNHAPs(tbl_CHITIETPHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PHIEUNHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_tbl_HOADON")]
	public partial class v_tbl_HOADON
	{
		
		private string _MaHD;
		
		private string _MaKH;
		
		private string _TenKH;
		
		private System.DateTime _Ngaylap;
		
		private string _TenNV;
		
		public v_tbl_HOADON()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this._MaHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="Date NOT NULL")]
		public System.DateTime Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this._Ngaylap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_loaisp")]
	public partial class v_loaisp
	{
		
		private string _Tenloai;
		
		private string _TenSP;
		
		public v_loaisp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this._Tenloai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SANPHAM")]
	public partial class tbl_SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSP;
		
		private string _MaloaiSP;
		
		private double _GiaSP;
		
		private string _Donvitinh;
		
		private double _Gianhap;
		
		private System.Nullable<int> _Soluong;
		
		private EntitySet<tbl_CHITIETHOADON> _tbl_CHITIETHOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMaloaiSPChanging(string value);
    partial void OnMaloaiSPChanged();
    partial void OnGiaSPChanging(double value);
    partial void OnGiaSPChanged();
    partial void OnDonvitinhChanging(string value);
    partial void OnDonvitinhChanged();
    partial void OnGianhapChanging(double value);
    partial void OnGianhapChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    #endregion
		
		public tbl_SANPHAM()
		{
			this._tbl_CHITIETHOADONs = new EntitySet<tbl_CHITIETHOADON>(new Action<tbl_CHITIETHOADON>(this.attach_tbl_CHITIETHOADONs), new Action<tbl_CHITIETHOADON>(this.detach_tbl_CHITIETHOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaloaiSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaloaiSP
		{
			get
			{
				return this._MaloaiSP;
			}
			set
			{
				if ((this._MaloaiSP != value))
				{
					this.OnMaloaiSPChanging(value);
					this.SendPropertyChanging();
					this._MaloaiSP = value;
					this.SendPropertyChanged("MaloaiSP");
					this.OnMaloaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSP", DbType="Float NOT NULL")]
		public double GiaSP
		{
			get
			{
				return this._GiaSP;
			}
			set
			{
				if ((this._GiaSP != value))
				{
					this.OnGiaSPChanging(value);
					this.SendPropertyChanging();
					this._GiaSP = value;
					this.SendPropertyChanged("GiaSP");
					this.OnGiaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this.OnDonvitinhChanging(value);
					this.SendPropertyChanging();
					this._Donvitinh = value;
					this.SendPropertyChanged("Donvitinh");
					this.OnDonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gianhap", DbType="Float NOT NULL")]
		public double Gianhap
		{
			get
			{
				return this._Gianhap;
			}
			set
			{
				if ((this._Gianhap != value))
				{
					this.OnGianhapChanging(value);
					this.SendPropertyChanging();
					this._Gianhap = value;
					this.SendPropertyChanged("Gianhap");
					this.OnGianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SANPHAM_tbl_CHITIETHOADON", Storage="_tbl_CHITIETHOADONs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<tbl_CHITIETHOADON> tbl_CHITIETHOADONs
		{
			get
			{
				return this._tbl_CHITIETHOADONs;
			}
			set
			{
				this._tbl_CHITIETHOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CHITIETHOADONs(tbl_CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SANPHAM = this;
		}
		
		private void detach_tbl_CHITIETHOADONs(tbl_CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SANPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Chitiethoadon")]
	public partial class v_Chitiethoadon
	{
		
		private string _MaHD;
		
		private string _MaSP;
		
		private string _TenSP;
		
		private string _Tenloai;
		
		private double _GiaSP;
		
		private int _Soluong;
		
		private string _Donvitinh;
		
		private double _Thanhtien;
		
		public v_Chitiethoadon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this._MaHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this._MaSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this._Tenloai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSP", DbType="Float NOT NULL")]
		public double GiaSP
		{
			get
			{
				return this._GiaSP;
			}
			set
			{
				if ((this._GiaSP != value))
				{
					this._GiaSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this._Soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this._Donvitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtien", DbType="Float NOT NULL")]
		public double Thanhtien
		{
			get
			{
				return this._Thanhtien;
			}
			set
			{
				if ((this._Thanhtien != value))
				{
					this._Thanhtien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Thongkedoanhthu")]
	public partial class v_Thongkedoanhthu
	{
		
		private string _Mã_hóa_đơn;
		
		private System.DateTime _Ngày_bán;
		
		private string _Khách_hàng;
		
		private string _Số_điện_thoại;
		
		private System.Nullable<int> _Số_mặt_hàng;
		
		private System.Nullable<double> _Tổng_tiền;
		
		public v_Thongkedoanhthu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã hóa đơn]", Storage="_Mã_hóa_đơn", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_hóa_đơn
		{
			get
			{
				return this._Mã_hóa_đơn;
			}
			set
			{
				if ((this._Mã_hóa_đơn != value))
				{
					this._Mã_hóa_đơn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày bán]", Storage="_Ngày_bán", DbType="Date NOT NULL")]
		public System.DateTime Ngày_bán
		{
			get
			{
				return this._Ngày_bán;
			}
			set
			{
				if ((this._Ngày_bán != value))
				{
					this._Ngày_bán = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Khách hàng]", Storage="_Khách_hàng", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Khách_hàng
		{
			get
			{
				return this._Khách_hàng;
			}
			set
			{
				if ((this._Khách_hàng != value))
				{
					this._Khách_hàng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số điện thoại]", Storage="_Số_điện_thoại", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Số_điện_thoại
		{
			get
			{
				return this._Số_điện_thoại;
			}
			set
			{
				if ((this._Số_điện_thoại != value))
				{
					this._Số_điện_thoại = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số mặt hàng]", Storage="_Số_mặt_hàng", DbType="Int")]
		public System.Nullable<int> Số_mặt_hàng
		{
			get
			{
				return this._Số_mặt_hàng;
			}
			set
			{
				if ((this._Số_mặt_hàng != value))
				{
					this._Số_mặt_hàng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tổng tiền]", Storage="_Tổng_tiền", DbType="Float")]
		public System.Nullable<double> Tổng_tiền
		{
			get
			{
				return this._Tổng_tiền;
			}
			set
			{
				if ((this._Tổng_tiền != value))
				{
					this._Tổng_tiền = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
